# Generated by Django 5.0.3 on 2024-06-10 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_article_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('Patient', 'Patient'), ('Therapist', 'Therapist')], default='Patient', max_length=20),
        ),
    ]
